### ISSUE TITLE
Docs page show "This site can’t be reached"

### ISSUE THREAD

**Issue by DalerAsrorov** [kosmetism/react-soundplayer#111]
The docs website cannot be reached. Either the link is broken or the website is not functional anymore. Would be great to have it back. Thank you!

https://labs.voronianski.com/react-soundplayer

**Comment by diamond-darrell** [comment]
more to it, if you click `on the website` link  from the examples section it leads to some scum site

**Comment by voronianski** [comment]
sorry for inconvenience, I've updated the link - https://labs.voronianski.dev/react-soundplayer/
