### ISSUE TITLE
Implement WaveSurfer.js

### ISSUE THREAD

**Issue by itsmidnightyo** [kosmetism/react-soundplayer#81]
It would be cool to have the ability to add a waveform like SoundCloud using [wavesurfer.js](https://wavesurfer-js.org/), but add the ability to drag / customize it within a component or something.

I was also wondering if 'react-soundplayer' has the ability to control multiple tracks and stand as a standalone player, and just call those tracks individually from somewhere else on the page?
If you can't tell, I am pretty new to React. 🔥

**Comment by olliekav** [comment]
@itsmidnightyo Not sure if you are still looking to do this, or if this helps anyone else but I hooked up Wavesurfer.js to generate the waveforms and React Soundplayer as the player here https://dj.olliekav.com, the GitHub repo is https://github.com/olliekav/dj.olliekav.com.

I'm still trying to fix an odd bug with setting the audio element for Wavesurfer so you'll see a couple of setTimeouts when playing/next/prev to avoid this but should give you some pointers to get going. I'm a rookie React guy so ignore any bad code ha.
