### ISSUE TITLE
Create Repeat track/all component

### ISSUE THREAD

**Issue by ridhwaans** [kosmetism/react-soundplayer#82]
It seems that react-soundplayer is missing a Repeat component for the soundcloud audio playlist.
Also, it would be nice to have a stack implementation of playlist history or recently played tracks

**Comment by voronianski** [comment]
The aim of this lib is to provide a list if components which can be used as building blocks for the audio players in React. Developers are the ones that will decide what type of player they want to create.

If you need an example of how playlist player can be created please check this one - https://github.com/kosmetism/react-soundplayer/blob/master/examples/players/PlaylistSoundPlayer.js.
