### ISSUE TITLE
Install react-soundplayer deletes react-scripts

### ISSUE THREAD

**Issue by mangione77** [kosmetism/react-soundplayer#83]
I have an issue when installing your lib.  

Every time I try to install it, after npm install react-soundplayer --save, everything goes fine, except when I try to run my React app with npm start - that's when i get:

`'react-scripts' is not recognized as an internal or external command`

It may be some conflict with your lib and npm.

I'm currently running Windows 10 Home, node v8.9.0 & npm 5.6.0

**Comment by voronianski** [comment]
Sounds unrelated to the lib. Let me know if the issue still occurs.
