### ISSUE TITLE
requestAudio in componentWillReceiveProps

### ISSUE THREAD

**Issue by scrat98** [kosmetism/react-soundplayer#86]
https://github.com/kosmetism/react-soundplayer/blob/2863b9d1ff8f233e45ace1610c959be3ccd2bbc9/src/addons/withSoundCloudAudio.js#L51

When you wnat dynamical update components with differents streamUrl - it will be fail because requestAudio invokes only once

**Comment by imhuyqn** [comment]
How do we solve this problem?

**Comment by scrat98** [comment]
@imhuyqn I used React ref and saved instance. And when I changed the URL I persist used ref.requestAudio. But next I switch to the "react-player" library as you can see here
https://github.com/scrat98/audio-streaming-site/commit/e51502ecfedbd221e2da0ad00456ee975e792a07

**Comment by jlariza** [comment]
Hi! I am having the same issue. Any updates on this bug?

**Comment by voronianski** [comment]
fixed via - https://github.com/kosmetism/react-soundplayer/pull/102
