### ISSUE TITLE
handleSeekTrack for custom audio

### ISSUE THREAD

**Issue by marsouin** [kosmetism/react-soundplayer#87]
Hi, thank you for this fantastic player. 
I was wondering if it was possible to handle clicks on the progress bar for non soundcloud players. In the component, `handleSeekTrack` requires soundCloudAudio which doesn't exist in a custom player. For now when I click it just resets the currentTime to zero...
Also it would be really nice not to have the clientID warning in `withSoundCloudAudio` when using a custom player. 
Thanks a lot for your help!

**Comment by hkjasf687261gh** [comment]
Hi, I also would love this feature to be able to seek through track with the progress bar for custom audio.

**Comment by sbrichardson** [comment]
This works currently, I’m not having any issues.
