### ISSUE TITLE
styles not loading

### ISSUE THREAD

**Issue by jlariza** [kosmetism/react-soundplayer#90]
Good day,

I am trying to use the library; I have implemented two examples (BasicSoundPlayer.js and ProgressSoundPlayer.js) but they styles are not loading. The components work, they start and stop the music when I hit play or pause, but they look like this on chrome

![image](https://user-images.githubusercontent.com/16421045/43961947-efa0bf80-9c7b-11e8-90ec-2c899cb9843c.png)

On firefox, the play button is giant and covers all the screen.

What am I missing? How should I load the styles?

Thank you,

**Comment by Matsyir** [comment]
Are you loading the styles with HTML? Load them in your React page where you load/create the players, using 'import "../nextcss/buttons.css"', or whatever the path is in your project. I had the same issue when loading the CSS through HTML. I don't know enough about React to tell you why this happens or how to change the behavior.

**Comment by voronianski** [comment]
In order to load styles you need to write proper paths to them. Use styles for components that you are using.

In JS:
```html
require('react-soundplayer/styles/buttons.css');
require('react-soundplayer/styles/cover.css');
// etc.

// use `import` in ES6
```

in HTML:
```html
<link rel="stylesheet" type="text/css" href="path/to/node_modules/react-soundplayer/styles/buttons.css">
<link rel="stylesheet" type="text/css" href="path/to/node_modules/react-soundplayer/styles/cover.css">
<!-- etc. -->
```
