### ISSUE TITLE
Change song by updating resolveUrl prop

### ISSUE THREAD

**Issue by bzhr** [kosmetism/react-soundplayer#98]
I am trying to update the URL for the song that is playing by updating the `resolveUrl` prop, however, after the update SoundPlayer still playst the same song. 

I set `resolveUrl` from the component state, something like this:
```

      <GlobalPlayer
        resolveUrl={this.state.url}
        clientId={clientId}
        onReady={() => {
          console.log("player url ready!");
        }}
      />
```

I know that I can pass a SC playlist, but I would like to be able to update this dynamically based on an event from songs that are not in a SC playlist. Is there a way to do this?

**Comment by bzhr** [comment]
Some context about my use case: I want to build a global player, like the bottom player on soundcloud, I am using React Context for this.

**Comment by xanderjakeq** [comment]
I ran into this problem and found a solution (maybe) thanks to this [solution on how to implement autoplay](https://github.com/kosmetism/react-soundplayer/issues/88#issuecomment-449553583). 
Here's my whole component:
```
const Player = props => {

	const {soundCloudAudio, streamUrl, trackTitle, currentTime, duration} = props;

	const [autoPlay, setAutoPlay] = useState(true);

	const prevUrl = usePrevious(streamUrl);

	useEffect(() => {
		if(autoPlay){
			soundCloudAudio.play({streamUrl}); //This seems to be the magic line
			setAutoPlay(false);
		} 
		if(prevUrl !== streamUrl) {
			setAutoPlay(true);
		}
	},[streamUrl])

	return (
		<PlayerContainer>
			<div id = 'options-container'>
				<PlayButton 
					{...props} 
					className="playButton">
				{Icons.PlayButton}
				</PlayButton>
				<h2>{trackTitle}</h2>
				<Timer {...props}/>
			</div>
			<Progress 
					{...props}
					className = 'progressBarContainer'
					innerClassName = 'progress'
					value = {(currentTime/duration)*100 || 0}/>
		</PlayerContainer>
	);

	// referenced https://stackoverflow.com/questions/53446020/how-to-compare-oldvalues-and-newvalues-on-react-hooks-useeffect
	function usePrevious(value) {
		const ref = useRef();
		useEffect(() => {
		  ref.current = value;
		});
		return ref.current;
	}
};
```
`soundCloudAudio.play({streamUrl})` will play the audio you have. Not sure if it will work with resolveUrl tho

**Comment by bzhr** [comment]
@xanderjakeq thanks for the reply. I will have a look and let you know if it solves my use case.

**Comment by bzhr** [comment]
@xanderjakeq I have forked this library and added a function to load a new song. 
This works fine expect when I want to play the next song with auto-play, without stopping. What happens is that the previous song will continue to play unless I press pause and then play again.

I think that what's happening is that the playback is continued before the new song is fully loaded, I don't know how to wait until the song is fully loaded.
Any idea maybe?

**Comment by bzhr** [comment]
I solved this by simulating two mouse clicks.
First one pauses the player, second one fires after a 0.5sec. timeout, enough for the new song to be loaded. Works perfectly, I now have a Global Soundcoud player with custom playlists that play uninterruptedly.

**Comment by voronianski** [comment]
fixed via - https://github.com/kosmetism/react-soundplayer/pull/102
